title: (r)Evolutions
markdown: kramdown
echange_libelle: "1h pour avancer"
echange_lien: echange.html
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      title: "(r)Evolutions"